### ISSUE TITLE
Revisit language around dynamic checks

### ISSUE THREAD

**Issue by lenary** [Microsoft/checkedc#105]
We should be clearer about dynamic checks. In some places we're slightly too explicit about where and when a dynamic check will happen. This should be changed to say something like "at or before <this point>" which allows us to hoist some dynamic checks.

We will probably have to reference a set of rules for how we hoist checks, in order to prevent us from hoisting checks too early, but these can be fleshed out later.

**Comment by dtarditi** [comment]
We don't want to do this.   It's easier and simpler to just say "the check occurs at program point p" or "at this point in evaluating an expression".  The compiler can move it earlier if it can prove that the meaning of the program doesn't change.

It would be complicated semantically to allow checks to be done "at or before" a program point.   When moving code around, we have to worry interference and memory mutation.    The problem with unspecified order of evaluation is already pretty bad in C.   C  leaves the order of evaluation of expressions undefined and allows control-flow and side-effects within expressions.  I prefer not to add to the problem.

The specific issue would be around things like struct accesses where the bounds might require accessing memory again.   Consider something like:
```
struct S {
  array_ptr<int> p;
  int len;
}

Now suppose we have something like
```
struct S *m;
g();
m->p[0]
```
How exactly do we say that the check for the subscript operation can be "moved earlier"?   The bounds are bounds(m->p, m->p + m->len).   Can we move it before g?  No, we can't because g could modify the object ponted to by m.
