### ISSUE TITLE
Question about validity check of bounds information

### ISSUE THREAD

**Issue by wonsubkim** [Microsoft/checkedc#145]
```
int *p;
ptr<int> q = 0;
array_ptr<int> r;
array_ptr<int> s : count(5) = 0;
int t checked[10];
```

```
// Expected result
q = (int*)p; // expected-error {{expression has no bounds}}
q = (int*)r; // expected-error {{expression has no bounds}}
q = (int*)s; // expected-error {{expression has no bounds}}
q = (int*)t; // expected-error {{expression has no bounds}}
```
In above example code, there are 4 explicit type casting to unchecked pointer type
Since explicit type casting to unchecked type `(int *)` ignores bounds information of source,
I expects that above 4 explicit type castings produces error "expression has no bounds"

```
// Actual result
q = (int*)p; // expected-error 2 {{expression has no bounds}}
q = (int*)r; // expected-error 2 {{expression has no bounds}}
q = (int*)s;
q = (int*)t;
```
Actually, only uppermost two cases produces error "expression has no bounds"
because only variable p & r does not have proper bounds expression.

Is it correct error for semantic for bounds expression? Can you explain why it is correct?

**Comment by dtarditi** [comment]
It is actually the opposite of what you are thinking:  bounds inference ignores cast expressions.  A cast expression does not change the bounds of a pointer.   One way to think about this is the following.  Suppose we wrote:
```
array_ptr<int> q : count(5) = (array_ptr<int>) ((int *) s);
```
We would expect this to be valid because a cast to an `int *` and then back to an  `array_ptr<int>` does not change the value of the pointer.   It also does not change the bounds of the pointer.

**Comment by wonsubkim** [comment]
I have misunderstood the explicit casting behavior.
Can you let me know which section I can refer to this topic in checkedc-spec v0.6?
I did not remember what I have seen this issue.
Ch 4. describes the validity of bounds declaration but I did not get it

However, explicit casting to checked pointer type makes bounds information by checking bounds
For example, `(ptr<int>)` explicit casting produces inferred bounds information
So I have thought that explicit casting operation can generate bounds information.
Is it correct?

Implicit/explicit casting does not change any other declared bounds information of variable
Bounds information is propagates through operation.
Only dynamic bounds cast operation can change bounds information?

**Comment by dtarditi** [comment]
These questions have been answered.
