### ISSUE TITLE
const _Ptr<T> initialization too strict

### ISSUE THREAD

**Issue by mwhicks1** [Microsoft/checkedc#215]
This code fails to typecheck:
```
const _Ptr<int> foo(int a)
{
  const _Ptr<int> x;
  if (a)
    x = &a;
  else
    x = 0;
  return x;
}
```
The equivalent code in C (i.e., replacing `_Ptr<int>` with `int*`) does type  check. Thus it seems that gcc is using dataflow analysis to ensure const variables are initialized before they are used, but Checked C is not.

**Comment by lenary** [comment]
We added semantic analysis to look for an "initializer", as defined in the syntax (as in something on the right of an `=` on a declaration), which is slightly different from something being semantically initialized. 

In this case, you can of course do this:

```
const _Ptr<int> foo(int a)
{
  const _Ptr<int> x = a ? &a : 0 ;
  return x;
}
```

But I realise this is annoying change and may not always work, especially with more complicated conditions or initialisation logic. As David has said, we want to relax this initialisation logic eventually, and in the short term probably insert defaults. 

I looked at how clang and GCC do the same in compiler explorer, and they both give an error for this code: https://godbolt.org/g/51VWGN

(In particular, `const int*` is pointer to `const int`, so I believe we want `int * const` which is const pointer to int, in unchecked types. God I hate how C does pointer declarations.

**Comment by dtarditi** [comment]
As @lenary said, both GCC and clang give errors when const Ptr<int> is replaced by int * const.     Unless I'm misunderstanding something this isn't a bug in the Checked C implementation or design.
