### ISSUE TITLE
Converting from zero-terminated char* to _Array_ptr

### ISSUE THREAD

**Issue by mwhicks1** [Microsoft/checkedc#216]
I have the following code that I'm in the middle of porting. What I'd like to be able to do is take the length of a normal C string, and then use that as the bounds when converting that string to an arrayptr. (Later, I'll convert the char* to a Checked C zero-terminated type, but I want to avoid that for now, to avoid the problem of cascading issues to fix.)

Here's the code, mid-port:
```
void
str_alloc_text(_Ptr<struct mystr> p_str, const char* p_src)
{
  unsigned int len = vsf_sysutil_strlen(p_src);
  _Array_ptr<const char> p_src_tmp : count(len) = p_src; /* ERROR */
  private_str_alloc_memchunk(p_str, p_src_tmp, len);
}
```
The function `private_str_alloc_memchunk` has the type
```
void
private_str_alloc_memchunk(_Ptr<struct mystr> p_str,
			   _Array_ptr<const char> p_src : count(len),
                           unsigned int len)
```
The problem is marked ERROR, and the compiler reports `error: expression has no bounds, initializer expected to have bounds because the variable being declared has bounds`. I'm not surprised about this, I just want to know how to best work around it.

**Comment by dtarditi** [comment]
I recommend using an assume_bounds_cast for now:
```
  _Array_ptr<const char> p_src_tmp : count(len) = _Assume_bounds_cast<_Array_ptr<const char>>(p_src, len);
```
We don't have `where` clauses or flow-sensitive bounds implemented, so we have now way of  connecting `len` to the length of p_src right now,   That's why I'm recommending that you use an _Assume_bounds_cast.   In the future we'd like to be able to write something like:
```
void
str_alloc_text(_Ptr<struct mystr> p_str, const char* p_src : itype(_Nt_array_ptr<char>))
{
  unsigned int len = vsf_sysutil_strlen(p_src) where p_src : count(len);
  _Array_ptr<const char> p_src_tmp : count(len) = p_src;
  private_str_alloc_memchunk(p_str, p_src_tmp, len);
}
```

**Comment by mwhicks1** [comment]
This seems not to work, complaining at use of the keyword `where`.
```
str.c:98:47: error: expected ';' at end of declaration
  unsigned int len = vsf_sysutil_strlen(p_src) where p_src : count(len);
                                              ^
                                              ;
```
Perhaps I don't have access to Nt_array_ptrs in my build? When I pulled this morning I only downloaded some branch stuff; there was nothing on the main trunk.

**Comment by mwhicks1** [comment]
That worked. Thanks.
