### ISSUE TITLE
void* types in checked blocks

### ISSUE THREAD

**Issue by mwhicks1** [Microsoft/checkedc#218]
When are `void *` types allowed in checked blocks? What if they are used, in those blocks, totally abstractly? I.e., we just copy them around, or pass them to outside functions that take `void *` as arguments?

Right now I am porting a hashtable module and it uses `void *` for keys and values, and it uses function pointers for producing hashcodes from these. All other pointer uses in the function are checked, and I'd like to enforce they are used properly. For this definition:
```
typedef unsigned int (*hashfunc_t)(unsigned int, void*);
```
I get the error
```
./hash.h:11:50: note: 'hashfunc_t' (aka 'unsigned int (*)(unsigned
      int, void *)') is not allowed in a checked scope
```

**Comment by lenary** [comment]
So the error you're getting here refers to the hashfunc_t having unchecked function pointer type.

It's checked type is `_Ptr<unsigned int(unsigned int, void*)>` but this still contains an unchecked type. 

I haven't solved this issue in the generic hash implementation I came across. It may be exactly where we have use `unchecked` until we get generics. I can't remember why we ban `_Ptr<void>` or why it won't work, but i don't think it will work.

**Comment by mwhicks1** [comment]
I switched to using `_Ptr<void>` and managed to get it to work. I'm not sure what the rules are but in the compiler I trust!

**Comment by lenary** [comment]
Yeah, explicit casts cannot remove checkedness, but i think we ensure (for the moment, until generics land) that pointer to void is still compatible with pointer to T.
