### ISSUE TITLE
Bug: Addr-of to init a struct

### ISSUE THREAD

**Issue by mwhicks1** [Microsoft/checkedc#221]
This code crashes the compiler:
```
int x;
_Ptr<int> px = &x; /* OK */
struct foo { _Ptr<int> p_variable; };
struct foo f = { &x }; /* Crashes compiler */
```
That it's done in a struct initializer is the key problem.

**Comment by dtarditi** [comment]
The pull request https://github.com/Microsoft/checkedc-clang/pull/408 has a fix for this issue.

**Comment by dtarditi** [comment]
This is fixed now - thanks for the report!
