### ISSUE TITLE
How to write functions that do foo(void *buf, unsigned int len)

### ISSUE THREAD

**Issue by mwhicks1** [Microsoft/checkedc#226]
I have a few functions that are of the form
```
void foo(void *buf : bytecount(len), unsigned int len) 
...
```
What's the "Checked C way" to write these, e.g., so I can typecheck the code in checked mode?

**Comment by dtarditi** [comment]
Usually, you can use array_ptr<void> in place of void *.  We allow conversions to/from array_ptr<void> in the same way that conversions to void * are allowed.

The following code compiles fine:
```
void foo(_Array_ptr<void> : byte_count(len), unsigned len);

void test(_Array_ptr<int> arg1 : count(len), _Array_ptr<float> arg2 : count(len), int len) {
  foo(arg1, len * sizeof(int));
  foo(arg2, len * sizeof(float));
}
```

**Comment by mwhicks1** [comment]
What if you change your test function to be:
```
int x;
foo(&x,sizeof(x));
```
?

**Comment by dtarditi** [comment]
That should work fine.  In a checked scope, `&x` has type `_Array_ptr<int>`, which converts to `_Array_ptr<void>`.  In an unchecked scope, it has type `int *` and that converts to `_Array_ptr<void>` too.
