### ISSUE TITLE
Counts on nested pointers

### ISSUE THREAD

**Issue by mwhicks1** [Microsoft/checkedc#228]
I want to write something like this:
```
void vsf_secbuf_alloc(_Ptr<_Array_ptr<char>> p_ptr : count(size), unsigned int size);
```
where the `count(size)` applies to the nested array pointer. Is there a way to do this, or to work around not being able to do it?

**Comment by dtarditi** [comment]
There isn't a way to express this in Checked C at this time.  In this specific case, the function has a void return type.  You could modify it to to return the value.

If that's not an option, the way to handle this safely right now is to introduce wrapper struct that expresses the constraints.  Yes, that does change data layout, so it is not ideal:
```
struct Safe_wrapper {
   _Array_ptr<char> my_ptr : count(size);
   int size;
}

void vsf_secbuf_alloc(_Ptr<struct Safe_wrapper> p_ptr, unsigned int size);
```
Section 7.3 of the Checked C spec discusses some speculative ideas for directly allowing pointers to _Array_ptrs.  I think this takes us right to where Deputy left off, which is dealing with aliasing.   I think dependent typing systems would have problems with aliasing.  See the spec for more details.

**Comment by mwhicks1** [comment]
Good point about the return value. I'll give that a whirl.
