### ISSUE TITLE
Allow checked function pointer types?

### ISSUE THREAD

**Issue by mwhicks1** [Microsoft/checkedc#230]
Are these possible? When I try to use the following type in checked mode, the compiler complains:
```
typedef int (*str_netfd_read_t)(_Ptr<struct vsf_session> p_sess,
				_Array_ptr<char> p_buf : count(len),
                                unsigned int len);
```
In particular, it complains about this prototype, and I'm assuming the reason is that the above typedef is not considered checked.
```
int str_netfd_alloc(_Ptr<struct vsf_session> p_sess,
		    _Ptr<struct mystr> p_str,
		    char term,
		    _Array_ptr<char> p_readbuf : count(maxlen),
		    unsigned int maxlen,
		    str_netfd_read_t p_peekfunc,
		    str_netfd_read_t p_readfunc);
```

**Comment by lenary** [comment]
The checked version of that type is:

```
_Ptr<int(_Ptr<struct vsf_session> p_sess, 
  _Array_ptr<char> p_buf : count(len), 
  unsigned int len)>
```

You could could provide a typedef like so:

```
typedef _Ptr<int(_Ptr<struct vsf_session> p_sess, 
  _Array_ptr<char> p_buf : count(len), 
  unsigned int len)> checked_str_netfd_read_t;
```

And then use `itype(checked_str_netfd_read_t)` on the parameters.

**Comment by dtarditi** [comment]
Yes, the problem is the use of an unchecked pointer to a function (that `*` in the typedef).   Sam's answer is the right approach.
