### ISSUE TITLE
Cast from _Ptr<void> to another type (polymorphism workaround)

### ISSUE THREAD

**Issue by mwhicks1** [Microsoft/checkedc#231]
I have a generic hashtable that gets/returns things of type `_Ptr<void>`. I'm trying cast back the thing I get out, in an unchecked block. But the compiler won't let me:
```
  _Array_ptr<const unsigned char> p : count(sz) = 0;
  _Unchecked { p = _Assume_bounds_cast<_Array_ptr<const unsigned char>>(p,sz); }
```
This gives me an error (below); what should I do instead?
```
standalone.c:276:80: error: count bounds expression not allowed for a void
      pointer return type
```

**Comment by lenary** [comment]
Attempt to use `byte_count(sizeof(real type) * sz)`. I believe the problem is that `void` has 0 size, and `p + i` is not necessarily defined if `p` is a pointer-to-void type (as `+` with pointers takes into account pointeee size)

**Comment by dtarditi** [comment]
I investigated and the error message looks like a genuine compiler bug.

My suggested workaround for now is to change the body of the function to be  unchecked and to revert p back to an unchecked pointer:
```
const unsigned char *p;
```
You can then cast the  `_Ptr<void>` variable v to `p`:
```
p = (const unsigned char *) v;
```
You don't need an `_Assume_bounds_cast` to cast to an unchecked pointer type.  You can just do a C-style cast.

**Comment by dtarditi** [comment]
I've opened https://github.com/Microsoft/checkedc-clang/issues/409 to track the compiler issue.
