### ISSUE TITLE
Checked/Unchecked Expressions

### ISSUE THREAD

**Issue by lenary** [Microsoft/checkedc#241]
At the moment, checked and unchecked region specifiers occur only at the block (or pragma) level. 

It would be useful to have a way of specifying that an expression (and all its subexpressions) were unchecked (or checked). This would allow us to have unchecked regions encase only a single expression that is a subexpression of another, say allowing a function parameter to be in its own unchecked region without affecting either other parameter computation, or the checkedness of the call; or allow `x && y` to have one side be unchecked.

**Comment by dtarditi** [comment]
I think it would be good to avoid fine-grained interleaving of checked and unchecked code.  While this makes conversion of code to Checked C easier, it makes verifying that blocks of code are checked harder.

I'm thinking about going in the other direction and adding a variant of checked scopes that is transitive.  For example, we could allow a block or function to be tagged with the `transitive` in addition to `checked`.   In such a scope, no nesting of unchecked blocks would be allowed, and only transitively checked functions could be called:
```
checked transitive { 
    ...
}
```
My caution about adding such a construct is that such scopes have *viral* effects.   Converting code requires everything it calls be modified.  In addition,  if you find out later on that some unchecked code needs to be called deep within a chain of checked scopes, all the enclosing scopes have to be modified.
