### ISSUE TITLE
Check-in PDF of technical report

### ISSUE THREAD

**Issue by madhur13490** [Microsoft/checkedc#262]
I see that the documentation is missing but there are some technical report latex files. It is better to check-in pdf also so that one can have a quick look. Moreover, a wiki is also useful.

**Comment by awruef** [comment]
Thanks for the comment! A PDF of the specification is available as a "release" here: https://github.com/Microsoft/checkedc/releases

**Comment by dtarditi** [comment]
@madhur13490, I agree with your comment about the wiki.  It's on our "to do" list to improve it. Thanks!

**Comment by dtarditi** [comment]
I updated the readme to make this clearer.
