### ISSUE TITLE
Conversion of checked array types to pointer types

### ISSUE THREAD

**Issue by nmeum** [Microsoft/checkedc#272]
Since you seem to appreciate feedback about the Checked C extension itself we wanted to inform you about an issue we were having with the conversation rules for checked arrays which made it more difficult for us to convert our code base to Checked C.

The conversation rules for checked Arrays are defined in Section 2.5.2 of version `v0.7` of the Checked C specification as follows:

> If the type of an expression is “checked array of T”, the type of the expression is altered to be array_ptr<T>. If the type of an expression is “checked null-terminated array of T ”, the type of the expression is altered to be nt_array_ptr<T>.
    
We didn't want to convert everything at once and thus used a one-module-at-a-time approach which causes some issues with the conversion rule cited above.

For instance, assume you have the following struct definition in a header file:

```C
struct Foo {
  char a[23];
}
```

When converting the header file defining this struct you would convert it as follows:

```C
struct Foo {
  char a _Checked[23];
}
```

However, this may cause other (not yet converted) parts of your software to no longer compile. One example for Legacy C code that would no longer compile with the new struct definition is:

```C
void myfunc(struct Foo *foo) {
  char *p = foo->a; // needs to be changed to (char*)foo->a
}
```

This behaviour is explained in Section 5.2 of the Checked C specification:

> Implicit conversions from checked pointer types to unchecked pointer types are not allowed because that would cause a loss of bounds safety.

The code above can, however, be fixed by using an explicit cast to an unsafe pointer type. It would be neccessary though to find and changes all Legacy C parts of the codebase where the `a` member of `struct Foo` is used as a pointer, which makes conversation more difficult in our experience.

You don't have this problem with `struct members` of a pointer type because you can use bounds-safe interfaces for those. We are therefore wondering if it would be possible to introduce a 'bounds-safe checked array type' or to make the conversation rules for checked Array types more relaxed to allow **implicit** conversations of Checked Arrays to unsafe pointer types in unchecked program scope? This would definitly increase interoperability with Legacy C code parts.

**Comment by dtarditi** [comment]
Thank you for your thoughtful feedback.  I think we already have a solution for this issue.  You can use "bounds-safe interface types" to provide an alternate checked type for arrays:
```
struct Foo {
   char a[23] : itype(char _Checked[23]);
};
```
Interface types allow you to declare a "more checked" version of a type to be used in a checked scopes.  They were originally added to handle things like:
```
struct S {
   int **p;
}
```
What should the type of the inner pointer (`int *`) be?   You can answer that by providing an `itype`:
```
struct S {
  int **p : itype(_Ptr<_Ptr<int>>);
};
```
The type in an itype must be structurally identical to the original type, except that it must be "more checked", with `a *` replaced by `_Ptr` or '_Array_ptr` or an array replaced by a checked array.  For the purpose of allowing incremental coversion, the type doesn't have to fully checked.  It is OK to have something like:
```
struct S {
  int **p : itype(_Ptr<int *>);
};
```

**Comment by nmeum** [comment]
> You can use "bounds-safe interface types" to provide an alternate checked type for arrays

I didn't know that "bounds-safe interface types" also work for checked arrays. This is indeed exactly what I was looking for. Thanks for pointing this out and sorry for bothering you.

**Comment by dtarditi** [comment]
The specification only discussed pointers with bounds-safe interfaces.  I've updated it so that it is clear that array variables and members can have bounds-safe interfaces too.
