### ISSUE TITLE
Convert malloc and other memory functions that use "void *" to polymorphic generic functions

### ISSUE THREAD

**Issue by Prabhuk** [Microsoft/checkedc#305]
1. Replace the signature of malloc and other standard library functions that use "void *" to polymorphic generic function signature, by introducing _Itype_for_any function specifiers.
2. This will break tests that invoke the functions and will require call sites to issue type variables (from within checked code). Fix these tests.

**Comment by dtarditi** [comment]
This was completed by PR https://github.com/Microsoft/checkedc/pull/315 and PR https://github.com/Microsoft/checkedc-llvm-test-suite/pull/88.
