### ISSUE TITLE
Use Intel MPX to speed up runtime boundary checks

### ISSUE THREAD

**Issue by marcusbotacin** [Microsoft/checkedc#321]

**Comment by dtarditi** [comment]
@marcusbotacan, I agree that we could use the Intel MPX instructions for bounds comparisons to speed up the runtime bounds checks.   We could the MPX bounds registers to hold bounds.  The `bndmk`, `bndcl`, and `bndcu` instructions could be used to load bounds, check lower bounds, and check upper bounds, respectively.

Note that Checked C doesn't compute bounds until they are needed.  There would need to be a compiler optimization that precomputes bounds for loops.

Using the MPX instructions is a compiler issue, not a language issue.  Could you file this issue against the clang implementation of Checked C at https://github.com/Microsoft/checkedc-clang?

**Comment by marcusbotacin** [comment]
Done. https://github.com/Microsoft/checkedc-clang/issues/565
