### ISSUE TITLE
Incorrect header name "checkedc.h"

### ISSUE THREAD

**Issue by mgrang** [microsoft/checkedc#356]
https://github.com/microsoft/checkedc/blob/ee58a670bbac94530605ad913eccac0541553c06/spec/bounds_safety/core-extensions.tex#L52

The correct header should be stdchecked.h

**Comment by dtarditi** [comment]
Please go ahead and correct this to match the file name in the Checked C source code.

**Comment by mgrang** [comment]
Fixed in a7fbe45.
