### ISSUE TITLE
Decide what to do about old-style C function declarations

### ISSUE THREAD

**Issue by dtarditi** [Microsoft/checkedc#36]
C allows old-style function declarations where the types of function arguments are not checked at function calls.  For example, you can write:

int f();

The function 'f' returns an integer, but takes unspecified arguments.   Arguments are passed at the call site based on their types and some well-specified conversions to ints and doubles.

This is inherently unsafe because a mismatch between a function definition and function call in the number of arguments or the types of the arguments can corrupt the program call stack.

My initial proposal is the following:
- We not allow bounds declarations to be used with old-style C function declarations. 
- We disallow passing arguments with checked pointer types to functions declared using old-style declarations.
- We disallow calls to functions declared with old-style declarations in checked scopes.  Even if checked pointers are not passed, the stack can still be corrupted.

Of course, a function can be declared with an old-style declaration and then have a subsequent redeclaration that adds the parameter list.    The above rules would apply only to code that is only in the scope of the old-style declaration.

I am interested in feedback about this proposal.

**Comment by reubeno** [comment]
Totally agreed--your proposal sounds like a great plan.  I do want to note, though, that mismatches between declaration and definition (say, across multiple .c files) form a larger problem--and this is a special case of that.  Right?

**Comment by dtarditi** [comment]
This specification was updated by pull request #66 to include these changes, so I'm closing this issue.
