### ISSUE TITLE
assert_checked.h conflicts with the internal assert.h on Mac

### ISSUE THREAD

**Issue by kyleheadley** [microsoft/checkedc#424]
I'm trying out checked-c-clang by compiling https://github.com/kokke/tiny-bignum-c
most of it works fine, but I get errors with assert. For example, if I augment the #include headers in bn.c and bn.h with "_checked" and run clang on bn.c, I get errors:

```
assert_checked.h:30:13: warning: 
      type specifier missing, defaults to 'int' [-Wimplicit-int]
extern void __assert(const char *msg : itype(_Nt_array_ptr<const char>), 
            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/assert.h:88:20: note: 
      expanded from macro '__assert'
    __assert_rtn ((const char *)-1L, file, line, e)
                   ^
```
```
assert_checked.h:30:13: error: 
      expected ')'
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/assert.h:88:33: note: 
      expanded from macro '__assert'
    __assert_rtn ((const char *)-1L, file, line, e)
                                ^
/Users/kyleheadley/Documents/Projects/3C/include_checked/assert_checked.h:30:13: note: 
      to match this '('
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/assert.h:88:18: note: 
      expanded from macro '__assert'
    __assert_rtn ((const char *)-1L, file, line, e)
                 ^
```
```
assert_checked.h:30:13: error: 
      conflicting types for '__assert_rtn'
extern void __assert(const char *msg : itype(_Nt_array_ptr<const char>), 
            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/assert.h:88:5: note: 
      expanded from macro '__assert'
    __assert_rtn ((const char *)-1L, file, line, e)
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/assert.h:76:6: note: 
      previous declaration is here
void __assert_rtn(const char *, const char *, int, const char *) __dead2 __d...
     ^
```
and a couple others.

The code uses assert with a bool, so there's no obvious checking requirements, but I'd like to use all the available checked headers if possible.

**Comment by mwhicks1** [comment]
Just to add: If on a Mac you compile 
```
#include <assert_checked.h>
```
and compile with Checked C's `clang` on a Mac, you get errors quite similar to the ones Kyle has given above.

**Comment by mgrang** [comment]
Thanks for reporting the issue @kyleheadley and @mwhicks1. This seems to be a Mac-specific issue. I tried building tiny-bignum on Linux with checked headers and could build without errors. Currently, Windows and Linux are the only supported platforms for the Checked C compiler.

@dtarditi Could you please comment on Mac support for the Checked C compiler.

**Comment by mwhicks1** [comment]
FYI, we have forked `checkedc` and our clone has a fix that works on my Mac, for this issue. See https://github.com/correctcomputation/checkedc/blob/master/include/assert_checked.h

**Comment by dtarditi** [comment]
@mwhicks1, we'd be happy to take your fix.   To clarify on @mgrang's comments, we are interested in Mac working too.  We're just not set up to do testing for the Mac.

**Comment by mgrang** [comment]
@mwhicks1, Thanks for the fix. Could you open a PR so that we can get this merged?

**Comment by mwhicks1** [comment]
Done. https://github.com/microsoft/checkedc/pull/427

**Comment by mgrang** [comment]
Fix is now merged in master.
