### ISSUE TITLE
Use `#include_next` to avoid the need for user code to modify includes to point to Checked C headers

### ISSUE THREAD

**Issue by mattmccutchen-cci** [microsoft/checkedc#431]
IIUC, the reason the Checked C system headers have names like `foo_checked.h` rather than `foo.h` is so that they can `#include <foo.h>` and get the underlying system `foo.h` rather than infinite recursion.  But Clang has a feature designed to solve precisely this problem so user code can `#include <foo.h>` as it always did, removing a significant eyesore.  The feature is called `#include_next`.  Not all C compilers support `#include_next` ([GCC does](https://gcc.gnu.org/onlinedocs/cpp/Wrapper-Headers.html), for one), but unless you foresee adding support for Checked C to a compiler that doesn't support `#include_next`, I think it is safe for us to introduce a dependency on it, since other C compilers won't even be able to parse Checked C code anyway.

So the way this will work: We ensure the Checked C include directory is earlier than the underlying system include directory on the include path, and the Checked C include directory contains a file `foo.h` that says `#include_next <foo.h>` and then has the Checked-C-specific declarations.  User code says `#include <foo.h>`.  This resolves to the Checked C header file because it is earlier on the include path.  Now, the `#include_next <foo.h>` there starts searching the include path from _the directory after the one in which the Checked C header was found_, so there is no infinite recursion and presumably it resolves to the underlying system header.

Are you open to moving to `#include_next`?  If so, I may try a PR.  For backward compatibility, we would keep each existing `foo_checked.h` file, containing the single line `#include <foo.h>`.

**Comment by sulekhark** [comment]
@mattmccutchen-cci, Thank you for your suggestion and offer, but at present, this is not high-priority for us. We want Checked C to be "opt-in" in spirit. In addition, at present, we prefer the existing simple and explicit way of including the `*_checked` headers to avoid causing confusion among users.

**Comment by mattmccutchen-cci** [comment]
FTR: @mwhicks1 said he discussed this proposal with the Microsoft team at a private meeting and they are considering it further.

**Comment by mattmccutchen-cci** [comment]
It looks like work on this has started in the [`implicit-include-of-hdrfiles` branch](https://github.com/microsoft/checkedc/compare/implicit-include-of-hdrfiles).  @sulekhark Can you please let me know when you think the change is working?  I can test it on our benchmark test suite by modifying the test script to skip the step that inserts `_checked` into the `#include` directives.

**Comment by sulekhark** [comment]
@mattmccutchen-cci  Sorry, I did not reply earlier. Yes, I will let you know!

**Comment by mattmccutchen-cci** [comment]
Done in #440 and microsoft/checkedc-clang#998. :tada:
