### ISSUE TITLE
semantics of realloc

### ISSUE THREAD

**Issue by mwhicks1** [microsoft/checkedc#437]
The header file for `realloc` gives it this type
```
_Itype_for_any(T) void *realloc(void *pointer : itype(_Array_ptr<T>) byte_count(1), size_t size) : itype(_Array_ptr<T>) byte_count(size);
```
I am wondering what happens when the size argument is *smaller* than the size of the passed-in pointer. Some versions of `realloc` will reuse the same buffer if it's big enough. Suppose I do `q = realloc(p,1024);` where `p`'s size is 2048, i.e., `q` is smaller so `p` and `q` could point to the same memory. Now suppose a later call to `malloc` reuses the 1024 bytes the call to `realloc` gave up. Then, running `p[1025]` would be a spatial safety violation.

OTOH, according to the POSIX [`realloc` man page](https://www.unix.com/man-page/posix/3p/realloc/), `realloc` should always be considered to free the memory associated with its argument. By that interpretation, any dereference of `p` after the call `realloc(p,...)` is a temporal safety violation; i.e., Checked C doesn't purport to help there.

Maybe there's nothing to do with the code here, but perhaps this can be mentioned in the manual.

**Comment by mattmccutchen-cci** [comment]
> OTOH, according to the POSIX [`realloc` man page](https://www.unix.com/man-page/posix/3p/realloc/), `realloc` should always be considered to free the memory associated with its argument. By that interpretation, any dereference of `p` after the call `realloc(p,...)` is a temporal safety violation; i.e., Checked C doesn't purport to help there.

FWIW, the above is my point of view.

**Comment by sulekhark** [comment]
Thanks Mike and Matt. I agree that after `realloc(p, ...)` any dereference of `p` is a temporal safety violation. I will add a section in the spec stating that at present Checked C does not purport to detect temporal memory safety violations and explain the particular case of `realloc`.

**Comment by sulekhark** [comment]
Documented.
