### ISSUE TITLE
Wiki Example of _Nt_array_ptr Bounds Widening Does Not Work

### ISSUE THREAD

**Issue by PappasBrent** [microsoft/checkedc#446]
Hi,

I wrote the following code adapted from [this example](https://github.com/microsoft/checkedc/wiki/New-pointer-and-array-types#pointers-to-null-terminated-arrays) in the Checked C Wiki to test the bounds-widening functionality of the _Nt_array_ptr type:

```c
#include <stdio_checked.h>
#include <stdlib_checked.h>

int getlen(_Nt_array_ptr<char> p : count(0)) {
  int len = 0;
  _Nt_array_ptr<char> t : count(len) = p;
  while (t[len]) {
    len++;  // widens bounds of t by 1.
  }
  return len;
}

int main(int argc, _Array_ptr<_Nt_array_ptr<char>> argv : count(argc) ) {
    if (argc > 1) {
        printf("%s\n", argv[1]);
        int len = getlen(argv[1]);
        printf("Len: %d\n", len);
    }
    return 0;
}
```

I installed the [latest Win64 release of Checked C Clang](https://github.com/microsoft/checkedc-clang/releases/tag/CheckedC-Clang-11.1.0-rel1) to compile this program. Upon running `clang`, however, I was greeted with the following error and notes:
```
test.c:8:5: error: inferred bounds for 't' are unknown after increment
    len++;  // widens bounds of t by 1.
    ^~~~~
test.c:6:23: note: (expanded) declared bounds are 'bounds(t, t + len)'
  _Nt_array_ptr<char> t : count(len) = p;
                      ^
test.c:8:5: note: lost the value of the variable 'len' which is used in the (expanded) inferred bounds
      'bounds(t, t + len + 1)' of 't'
    len++;  // widens bounds of t by 1.
    ^~~
1 error generated.
```

The section of code that is reported to be causing the error is directly copied from the wiki. Am I doing something wrong, is this feature still under development, or is there an error with the bounds-widening capability of the _Nt_array_ptr type?

[Here is a txt file](https://github.com/microsoft/checkedc/files/6460416/test.txt) containing the code I used to produce this error.

**Comment by kkjeer** [comment]
@PappasBrent, thank you for reporting this issue! The example in the wiki is not working as expected; we will update the wiki to reflect this.

The bounds widening feature for null-terminated arrays is currently working as expected. However, both bounds widening and the bounds validation need to be enhanced in order to validate bounds within loops. We are continuing to work on the internal compiler machinery that supports these enhancements.
