### ISSUE TITLE
Checked C mailing list archive web site is down

### ISSUE THREAD

**Issue by mattmccutchen-cci** [microsoft/checkedc#451]
https://github.com/Microsoft/CheckedC/blob/master/MAILING-LISTS.md#archives says:

> To access the archive, go to https://lists.research.microsoft.com.

I'd like to view the archives so I can try to avoid asking questions that have been answered before.  But that link is not loading for me; I tried it from two different computers.  If the archive is no longer available, can you please update the documentation?  I tried [a quick web search](https://www.google.com/search?q=microsoft+research+mailing+list+archives) to see if the archive server had moved but found nothing useful; in fact, the first result was this repository's MAILING-LISTS.md itself.

The email interface seems to still work.  I submitted a request to subscribe to both mailing lists, which was held for approval.  I also submitted a help command and got:
```
> HELP

LISTSERV(R) version 16.0 - most commonly used commands

INFO      <topic|listname>       Order documentation (plain text files)
SUBscribe listname <full name>   Subscribe to a list
SIGNOFF   listname               Sign off from a list
SIGNOFF   * (NETWIDE             - from all lists on all servers
Query     listname               Query your subscription options
Search    listname  keyword...   Search list archives
SET       listname  options      Update your subscription options
INDex     <listname>             Order a list of LISTSERV files
GET       filename filetype      Order a file from LISTSERV

There are more commands; send an INFO REFCARD command for a comprehensive
reference card, or just INFO for a list of available documentation files.

If  you prefer,  you  can  use LISTSERV  through  its  web interface  at
http://lists.research.microsoft.com/scripts/wa.exe (the full manuals can
also be browsed online at this URL).

This server is managed by:
 wymanc@microsoft.com
 jeffrey.Chirico@microsoft.com
```
But searching the archives this way is going to be a pain, if it works at all.  (Should we ask those administrators for help?)

**Comment by sulekhark** [comment]
Thanks for trying this. We will either update the documentation or see how to fix the issue.

**Comment by dtarditi** [comment]
The archive is disabled because it is not GDPR compliant. We should document that the archive is disabled.

**Comment by mattmccutchen-cci** [comment]
Bummer.  I'd urge you to migrate from the mailing lists to another system that does have a public archive.  My experience is that a large fraction of the value of mailing lists for open-source projects is in their public archives: you can save both your time and that of your users if new users can find answers to some of their questions in the archive without having to ask again.  Would [GitHub Discussions](https://docs.github.com/en/discussions) work?

You could also consider publishing a one-time dump of the existing Checked C mailing list archives if you think the information there is still relevant and you can get GDPR approval (possibly after some redactions).

**Comment by sulekhark** [comment]
Moved to github discussions and updated the relevant pages in the readme files of the `checkedc-clang` repository.
