### ISSUE TITLE
Activate a checked declaration conditional on the existence of the original system declaration?

### ISSUE THREAD

**Issue by mattmccutchen-cci** [microsoft/checkedc#453]
On some systems, whether an original system header declares a program element may depend on a complex condition based on preprocessor definitions set by the user before including the header file.  In glibc, these definitions are called ["feature test macros"](https://linux.die.net/man/7/feature_test_macros).  An example of such an element that we're proposing to add in #448 is `get_current_dir_name` ([man page](https://linux.die.net/man/3/getcwd)).

If the checked headers provide a checked declaration of such a "conditional" element, ideally we'd like it to be active if and only if the original declaration is active.  Obviously, it would be a pain to reimplement the conditional logic in a way that is correct on all systems supported by Checked C.  I'd like a way to make the Checked C compiler ignore the checked declaration if a previous declaration of the same name has not already been seen in the translation unit.

(Fortunately, I'm not aware of any cases in which rather than just controlling whether a declaration exists at all, preprocessor definitions choose between several different versions of the declaration that would merit different checked declarations.)

Ditto my remark from #452 about taking this issue to the `checkedc-clang` repository.

**Comment by sulekhark** [comment]
I guess we have to live with explicitly using the the feature test macros for now. Such a feature as the one requested is not a top priority task at present.
