### ISSUE TITLE
discuss mixing of safe and unsafe types

### ISSUE THREAD

**Issue by dtarditi** [Microsoft/checkedc#9]
Do we want to allow unsafe pointers to point to safe pointers or vice versa?   What about arrays?  

Right now, the spec restricts multidimensional arrays so that all dimensions are checked or unchecked.  Because a multidimensional array is technically an array of array types, this is a restriction on mixing checked and  unchecked types.   No other restrictions are placed on mixing other kinds of safe and unsafe types.

**Comment by lenary** [comment]
There could be issues around unchecked pointers to checked ptr typed things, as discussed, where dereferencing the outer unchecked pointer doesn't give us a `ptr` that conforms to our expectations. This is especially an issue with function pointers where we have one or two additional conditions around assignment and compatibility.

**Comment by dtarditi** [comment]
This mixing seems necessary to allow incremental conversion of programs.
