### ISSUE TITLE
Fix non-portable tests of integers with bounds declarations.

### ISSUE THREAD

**Issue by dtarditi** [Microsoft/checkedc#92]
I built and ran the Checked C tests on Ubuntu Linux x64.   typechecking/bounds.c and typechecking/no_prototype_functions.c failed because of 32 vs. 64 pointer size differences.  We are trying to test integers with bounds declaration.   To test this, we need to cast some pointers to be integers.  We used int as the integer type in the tests, which does not work on a 64-bit platform. It causes a warning for no_prototype_functions.c because a smaller type is being cast to a pointer size.  It causes an outright error in bounds.c because the initializer for a static variable is no longer a compile-time constant.  We had already hit this attempting to test short integers on 32-bit platform.

I've reviewed the C specification and there is no portable way to write code that casts between pointers and integers.   For example, the C spec does not guarantee that size_t is actually large enough to hold a pointer value.   It does not guarantee that there is any integer type large enough to hold a pointer value, in fact.  At best, we can write some non-portable code for specific target platforms that tests this functionality.  Clang has test support for doing this.

This work item is to move the integer bounds tests to platform-specific tests and make sure that the tests only run on platforms where the tests are expected to work.  We should restrict the platforms to avoid the tests breaking on other platforms where assumptions may be different.

**Comment by dtarditi** [comment]
Here is the log information:

lit.py: /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/lit.cfg:138: note: using clang: '/home/dtarditi/gitcheckedc/gitllvm.obj/./bin/clang'
FAIL: checkedc :: checkedc/tests/typechecking/no_prototype_functions.c (7 of 15)
******************** TEST 'checkedc :: checkedc/tests/typechecking/no_prototype_functions.c' FAILED ********************
Script:
--
/home/dtarditi/gitcheckedc/gitllvm.obj/./bin/clang -cc1 -internal-isystem /home/dtarditi/gitcheckedc/gitllvm.obj/bin/../lib/clang/4.0.0/include -nostdsysteminc -verify -verify-ignore-unexpected=note -fcheckedc-extension /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/no_prototype_functions.c
--
Exit Code: 1

Command Output (stderr):
--
error: 'warning' diagnostics seen but not expected: 
  File /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/no_prototype_functions.c Line 47: cast to 'char *' from smaller integer type 'int'
  File /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/no_prototype_functions.c Line 47: cast to 'char *' from smaller integer type 'int'
  File /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/no_prototype_functions.c Line 232: cast to 'char *' from smaller integer type 'int'
  File /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/no_prototype_functions.c Line 232: cast to 'char *' from smaller integer type 'int'
  File /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/no_prototype_functions.c Line 232: cast to 'char *' from smaller integer type 'int'
  File /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/no_prototype_functions.c Line 232: cast to 'char *' from smaller integer type 'int'
  File /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/no_prototype_functions.c Line 246: cast to 'char *' from smaller integer type 'int'
  File /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/no_prototype_functions.c Line 246: cast to 'char *' from smaller integer type 'int'
  File /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/no_prototype_functions.c Line 246: cast to 'char *' from smaller integer type 'int'
  File /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/no_prototype_functions.c Line 246: cast to 'char *' from smaller integer type 'int'
10 errors generated.

--

********************
FAIL: checkedc :: checkedc/tests/typechecking/bounds.c (12 of 15)
******************** TEST 'checkedc :: checkedc/tests/typechecking/bounds.c' FAILED ********************
Script:
--
/home/dtarditi/gitcheckedc/gitllvm.obj/./bin/clang -cc1 -internal-isystem /home/dtarditi/gitcheckedc/gitllvm.obj/bin/../lib/clang/4.0.0/include -nostdsysteminc -verify -verify-ignore-unexpected=note -fcheckedc-extension /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/bounds.c
--
Exit Code: 1

Command Output (stderr):
--
error: 'error' diagnostics seen but not expected: 
  File /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/bounds.c Line 443: initializer element is not a compile-time constant
  File /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/bounds.c Line 449: initializer element is not a compile-time constant
  File /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/bounds.c Line 450: initializer element is not a compile-time constant
  File /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/bounds.c Line 451: initializer element is not a compile-time constant
  File /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/bounds.c Line 452: initializer element is not a compile-time constant
5 errors generated.

--

********************
Testing Time: 1.26s
********************
Failing Tests (2):
    checkedc :: checkedc/tests/typechecking/bounds.c
    checkedc :: checkedc/tests/typechecking/no_prototype_functions.c

  Expected Passes    : 13
  Unexpected Failures: 2

**Comment by dtarditi** [comment]
Re-add log file with correct formating.

```
lit.py: /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/lit.cfg:138: note: using clang: '/home/dtarditi/gitcheckedc/gitllvm.obj/./bin/clang'
FAIL: checkedc :: checkedc/tests/typechecking/no_prototype_functions.c (7 of 15)
******************** TEST 'checkedc :: checkedc/tests/typechecking/no_prototype_functions.c' FAILED ********************
Script:
--
/home/dtarditi/gitcheckedc/gitllvm.obj/./bin/clang -cc1 -internal-isystem /home/dtarditi/gitcheckedc/gitllvm.obj/bin/../lib/clang/4.0.0/include -nostdsysteminc -verify -verify-ignore-unexpected=note -fcheckedc-extension /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/no_prototype_functions.c
--
Exit Code: 1

Command Output (stderr):
--
error: 'warning' diagnostics seen but not expected: 
  File /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/no_prototype_functions.c Line 47: cast to 'char *' from smaller integer type 'int'
  File /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/no_prototype_functions.c Line 47: cast to 'char *' from smaller integer type 'int'
  File /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/no_prototype_functions.c Line 232: cast to 'char *' from smaller integer type 'int'
  File /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/no_prototype_functions.c Line 232: cast to 'char *' from smaller integer type 'int'
  File /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/no_prototype_functions.c Line 232: cast to 'char *' from smaller integer type 'int'
  File /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/no_prototype_functions.c Line 232: cast to 'char *' from smaller integer type 'int'
  File /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/no_prototype_functions.c Line 246: cast to 'char *' from smaller integer type 'int'
  File /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/no_prototype_functions.c Line 246: cast to 'char *' from smaller integer type 'int'
  File /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/no_prototype_functions.c Line 246: cast to 'char *' from smaller integer type 'int'
  File /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/no_prototype_functions.c Line 246: cast to 'char *' from smaller integer type 'int'
10 errors generated.

--

********************
FAIL: checkedc :: checkedc/tests/typechecking/bounds.c (12 of 15)
******************** TEST 'checkedc :: checkedc/tests/typechecking/bounds.c' FAILED ********************
Script:
--
/home/dtarditi/gitcheckedc/gitllvm.obj/./bin/clang -cc1 -internal-isystem /home/dtarditi/gitcheckedc/gitllvm.obj/bin/../lib/clang/4.0.0/include -nostdsysteminc -verify -verify-ignore-unexpected=note -fcheckedc-extension /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/bounds.c
--
Exit Code: 1

Command Output (stderr):
--
error: 'error' diagnostics seen but not expected: 
  File /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/bounds.c Line 443: initializer element is not a compile-time constant
  File /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/bounds.c Line 449: initializer element is not a compile-time constant
  File /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/bounds.c Line 450: initializer element is not a compile-time constant
  File /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/bounds.c Line 451: initializer element is not a compile-time constant
  File /home/dtarditi/gitcheckedc/llvm/projects/checkedc-wrapper/checkedc/tests/typechecking/bounds.c Line 452: initializer element is not a compile-time constant
5 errors generated.

--

********************
Testing Time: 1.26s
********************
Failing Tests (2):
    checkedc :: checkedc/tests/typechecking/bounds.c
    checkedc :: checkedc/tests/typechecking/no_prototype_functions.c

  Expected Passes    : 13
  Unexpected Failures: 2
```

**Comment by lenary** [comment]
It seems C does have a standard feature for this, `intptr_t` which is guaranteed to fit the integer representing a given pointer, in a portable manner (similar to `size_t`), I wonder if I should include some tests with it for all platforms, or not.

**Comment by dtarditi** [comment]
intptr_t is an optional type.  That means that implementations of C can choose to omit it.  It would be fine to use it for platforms where it is defined.
